### ISSUE TITLE
KeyError: "FUTR3D: 'FPNV2 is not in the models registry'"

### ISSUE THREAD

**Issue by drilistbox** [Tsinghua-MARS-Lab/futr3d#14]
Hi:
    I encounter the error in title before when I run plugin/futr3d/configs/lidar_cam/res101_01voxel_step_3e.py. It seems that the FPNV2 has not been defined in the relese paper. Will you update this? 
                                                                                                                                                                                                  Thanks a lot!

**Comment by Song-Jingyu** [comment]
The same problem here! I ended up using FPN instead of FPNV2. But I am not certain if this is the right practice. Hope the authors could clarify.

**Comment by xyaochen** [comment]
I have added FPNV2.
The only difference between FPNV2 and original FPN is https://github.com/Tsinghua-MARS-Lab/futr3d/blob/main/plugin/futr3d/models/necks/fpn.py#L157. This is aimed to solve https://github.com/Tsinghua-MARS-Lab/futr3d/issues/16 and will not affect the forward results.

**Comment by shb9793** [comment]
> I have added FPNV2. The only difference between FPNV2 and original FPN is https://github.com/Tsinghua-MARS-Lab/futr3d/blob/main/plugin/futr3d/models/necks/fpn.py#L157. This is aimed to solve #16 and will not affect the forward results.

Thanks a lot for your contribution! I have faced this problem yesterday.
