### ISSUE TITLE
mmcv version

### ISSUE THREAD

**Issue by LYX-SOUL** [Tsinghua-MARS-Lab/futr3d#33]
The package I installed is shown below：
![image](https://github.com/Tsinghua-MARS-Lab/futr3d/assets/77523024/b5ed294e-e6ea-4bb4-aefa-5275e97f64e3)

**ERROR**: MMCV==2.0.0 is used but incompatible. Please install mmcv>=1.3.17, <=1.8.0.
How to solve this problem？Thanks

**Comment by LYX-SOUL** [comment]
resloved

**Comment by MinkyoungCho** [comment]
How did you resolve this issue? Can you let me know the versions of the modules (like your above screenshot)?

**Comment by LYX-SOUL** [comment]
Available package versions：
![image](https://github.com/Tsinghua-MARS-Lab/futr3d/assets/77523024/b396bb3d-0aba-4d27-a9d5-ed767c647a95)

**Comment by sijieaaa** [comment]
The following also works for me:

mim install mmcv-full==1.6.2
mim install mmdet==2.28.0
mim install mmengine==0.7.4
mim install mmsegmentation==0.30.0

pip install numpy==1.20.3
pip install numba==0.53.0
