### ISSUE TITLE
total iterations per epoch 

### ISSUE THREAD

**Issue by MinkyoungCho** [Tsinghua-MARS-Lab/futr3d#40]
Hello, 

I am wondering why the total iterations per epoch (total_it_per_ep) is different than my estimates (even though detr3d training's total_it_per_ep matches what I estimated).

I am now using 4 GPUs, samples_per_GPU=10. So, the estimated number is 28130 (# training samples) / (4*10) = appeoximately 700 iters/epoch.

But, it shows 3090 iters/ epoch
`....  - mmdet - INFO - Epoch [8][1450/3090]	lr: 9.902e-04, eta: ....`

Why does this phenomenon happen?

Best,

**Comment by xyaochen** [comment]
We use CBGSDataset wrapper. You can find the details at https://github.com/Tsinghua-MARS-Lab/futr3d/blob/main/mmdet3d/datasets/dataset_wrappers.py and also in the original paper (https://arxiv.org/abs/1908.09492)

**Comment by MinkyoungCho** [comment]
Thanks!
