### ISSUE TITLE
camera-LiDAR-radar Result

### ISSUE THREAD

**Issue by Song-Jingyu** [Tsinghua-MARS-Lab/futr3d#8]
Hi,

Thanks for this amazing work. In the project website I think it's mentioned FUTR3D supports camera-LiDAR-radar fusion but I was not able to find any results and checkpoints mentioned in the paper and github. Could you please suggest the reason/thinking behind this? Thank you.

**Comment by xyaochen** [comment]
The camera-LiDAR-Radar fusion results are not promising. It slightly degenerates compared to camera-LiDAR fusion.
I think the radar points in nuScenes are too noisy, so it can't contribute to the results when LiDAR points are available.

**Comment by Song-Jingyu** [comment]
Thanks for your quick response. That's good to know!

**Comment by deepmeng** [comment]
Do you have a model config for 'camera-lidar-radar'?

**Comment by deepmeng** [comment]
> Do you have a model config for 'camera-lidar-radar'?

Solved already
